commerce_payment.commerce_payment_gateway.plugin.vantiv_onsite:
  type: commerce_payment_gateway_configuration
  mapping:
    version:
      type: string
      label: 'API Version'
    user:
      type: string
      label: 'Username'
    password:
      type: string
      label: 'Password'
    currency_merchant_map:
      type: mapping
      label: 'Currency -> Merchant ID mapping'
      mapping:
        default:
          type: string
          label: 'Default'
    proxy:
      type: string
      label: 'Proxy'
    paypage_id:
      type: string
      label: 'PayPage ID'
    batch_requests_path:
      type: string
      label: 'Batch requests path'
    litle_requests_path:
      type: string
      label: 'Litle requests path'
    sftp_username:
      type: string
      label: 'sFTP username'
    sftp_password:
      type: string
      label: 'sFTP password'
    batch_url:
      type: string
      label: 'Batch URL'
    tcp_port:
      type: string
      label: 'TCP port'
    tcp_timeout:
      type: string
      label: 'TCP timeout'
    tcp_ssl:
      type: boolean
      label: 'TCP SSL?'
    print_xml:
      type: boolean
      label: 'Print XML?'
    timeout:
      type: integer
      label: 'Timeout'
    report_group:
      type: string
      label: 'Report group'
    mode:
      type: string
      label: 'Integration mode'
    machine_name:
      type: string
      label: 'Machine name of the gateway instance'
